### ISSUE TITLE
Move this package to a more relevant GitHub organization?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaVersionControl/GitCommand.jl#38]
I'd like to move this package to a more relevant GitHub organization.

I'm having a hard time figuring out what the best organization is for this package. Maybe JuliaPackaging or JuliaLang?

@staticfloat @giordano What do you think?

**Comment by giordano** [comment]
Not sure what would be a good organisation.  I don't think this fits into JuliaLang and I have some doubts about JuliaPackaging too, but I'm not against moving there in principle

**Comment by DilumAluthge** [comment]
Hmmm. Maybe JuliaIO?

**Comment by DilumAluthge** [comment]
I definitely want to get it out of BCBI 😂

**Comment by DilumAluthge** [comment]
@stefankarpinski or @viralbshah might have some ideas

**Comment by StefanKarpinski** [comment]
I don't really know a relevant org, but I just created https://github.com/JuliaMisc and you can transfer it there if you want. We could also create a JuliaGit org that could hold this and LibGit2.

**Comment by ViralBShah** [comment]
Perhaps JuliaCI as a stopgap if we don't want to use more orgs?

**Comment by DilumAluthge** [comment]
JuliaGit or JuliaVersionControl would both work.

Anyway in the meantime I've moved it to JuliaMisc.

**Comment by StefanKarpinski** [comment]
I also created https://github.com/JuliaVersionControl and invited you.

**Comment by DilumAluthge** [comment]
Perfect, I think JuliaVersionControl is a good home.

Moved to JuliaVersionControl.
