### ISSUE TITLE
Any other breaking changes to make before 3.0.0?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaVersionControl/GitCommand.jl#54]
We have already made the following breaking changes:
1. Remove the REPL functionality (https://github.com/JuliaVersionControl/GitCommand.jl/pull/52)
2. Remove a deprecated method (https://github.com/JuliaVersionControl/GitCommand.jl/pull/51)

Are there any other breaking changes that we would like to make before we release GitCommand.jl version 3.0.0.

cc: @giordano @ericphanson

**Comment by giordano** [comment]
No, as it is now the package is pretty bare-bones, and the only function exposed have very simple APIs.  Only thing: document `@git_cmd` in the README?

**Comment by DilumAluthge** [comment]
> Only thing: document `@git_cmd` in the README?

Right now `@git_cmd` isn't public - I figured we would wait until we figure out interpolation (https://github.com/JuliaVersionControl/GitCommand.jl/issues/15) before we make it public.

**Comment by giordano** [comment]
Uh, ok, then the only public function is `git()`, I don't see many more breaking changes to be done at this point :smile:
